# Generated by Django 5.2.4 on 2025-09-28 08:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('CSI', 'Centre de Santé Intégré'), ('CS', 'Centre de Santé'), ('HOSPITAL', 'Hôpital'), ('MOBILE_CLINIC', 'Clinique mobile'), ('ASC', 'Agent de Santé Communautaire')], max_length=50)),
                ('level_of_care', models.CharField(choices=[('PRIMARY', 'Soins de santé primaire'), ('SECONDARY', 'Soins de santé secondaire'), ('HIV', 'Programme VIH'), ('MALARIA', 'Programme Paludisme'), ('TB', 'Programme Tuberculose'), ('NUTRITION', 'Programme Nutrition'), ('LABORATORY', 'Programme Laboratoire')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('NGO', 'ONG'), ('GOVERNMENT', 'Programme étatique'), ('INTERNATIONAL', 'Organisation internationale')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('access_level', models.CharField(choices=[('COORDINATION', 'Coordination'), ('PROJECT', 'Projet'), ('FACILITY', 'Formation sanitaire')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('health_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthfacility')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('therapeutic_class', models.CharField(blank=True, max_length=100)),
                ('indications', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('interactions', models.TextField(blank=True)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('barcode_gs1', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_facilities', models.ManyToManyField(blank=True, to='api.healthfacility')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='api.medicationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='prescriptions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('order_frequency_months', models.IntegerField(default=3)),
                ('delivery_delay_months', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('buffer_stock_months', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.donor')),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.healthfacility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_date', models.DateField()),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'unique_together': {('organization', 'project', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('PATIENT', 'Patient'), ('SERVICE', 'Service hôpital'), ('EXPIRED', 'Périmés/détériorés'), ('RETURN', 'Retour pharmacie')], max_length=20)),
                ('dispensation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DELIVERED', 'Délivrée'), ('PENDING', 'En attente'), ('PARTIAL', 'Livraison partielle')], default='PENDING', max_length=20)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('prescription_number', models.CharField(blank=True, max_length=100)),
                ('prescriber_name', models.CharField(blank=True, max_length=255)),
                ('patient_phone', models.CharField(blank=True, max_length=20)),
                ('patient_service', models.CharField(blank=True, max_length=100)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('patient_unique_id', models.CharField(blank=True, max_length=100)),
                ('care_type', models.CharField(blank=True, choices=[('CURATIVE', 'Curative'), ('PREVENTIVE', 'Préventive'), ('FOLLOW_UP', 'Suivi')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('prescription_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prescriptionphoto')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('EXPIRY_RISK', 'Risque de péremption'), ('STOCKOUT', 'Rupture'), ('PRE_STOCKOUT', 'Pré-rupture'), ('OVERSTOCK', 'Surstock'), ('ANTIBIOTIC_OVERUSE', 'Surutilisation antibiotiques'), ('MALARIA_EPIDEMIC', 'Alerte épidémique paludisme'), ('SERVICE_OVERCONSUMPTION', 'Surconsommation service')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('CRITICAL', 'Critique')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('quantity_ordered', models.PositiveIntegerField(default=0)),
                ('quantity_delivered', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical_stock', models.PositiveIntegerField()),
                ('physical_stock', models.PositiveIntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.inventory')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
                ('stock_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stockentry')),
            ],
        ),
        migrations.CreateModel(
            name='DispensationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dispensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.dispensation')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stockentry')),
            ],
        ),
        migrations.CreateModel(
            name='StockoutPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='api.medication')),
                ('substitute_medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_for', to='api.medication')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
            options={
                'unique_together': {('original_medication', 'substitute_medication', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='ConsumptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('quantity_consumed', models.PositiveIntegerField()),
                ('is_week_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'unique_together': {('organization', 'project', 'medication', 'week_number', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StandardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=True)),
                ('custom_code', models.CharField(blank=True, max_length=20)),
                ('custom_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'unique_together': {('organization', 'project', 'medication')},
            },
        ),
    ]
