# Generated by Django 5.2.4 on 2025-10-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Alerte', 'verbose_name_plural': 'Alertes'},
        ),
        migrations.AlterModelOptions(
            name='dispensation',
            options={'verbose_name': 'Dispensation', 'verbose_name_plural': 'Dispensations'},
        ),
        migrations.AlterModelOptions(
            name='dispensationitem',
            options={'verbose_name': 'Article dispensé', 'verbose_name_plural': 'Articles dispensés'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'Bailleur de fonds', 'verbose_name_plural': 'Bailleurs de fonds'},
        ),
        migrations.AlterModelOptions(
            name='healthfacility',
            options={'verbose_name': 'Formation sanitaire', 'verbose_name_plural': 'Formations sanitaires'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': "Article d'inventaire", 'verbose_name_plural': "Articles d'inventaire"},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Médicament', 'verbose_name_plural': 'Médicaments'},
        ),
        migrations.AlterModelOptions(
            name='medicationcategory',
            options={'verbose_name': 'Catégorie de médicaments', 'verbose_name_plural': 'Catégories de médicaments'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AlterModelOptions(
            name='prescriptionphoto',
            options={'verbose_name': "Photo d'ordonnance", 'verbose_name_plural': "Photos d'ordonnances"},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='stockentry',
            options={'verbose_name': 'Entrée en stock', 'verbose_name_plural': 'Entrées en stock'},
        ),
        migrations.AlterModelOptions(
            name='stockoutperiod',
            options={'verbose_name': 'Période de rupture', 'verbose_name_plural': 'Périodes de rupture'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
