# Generated by Django 5.2.4 on 2025-10-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_alert_options_alter_dispensation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='api.organization'),
        ),
        migrations.AddField(
            model_name='medicationcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_categories', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationcategory',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='medicationcategory',
            unique_together={('organization', 'code')},
        ),
    ]
