# Generated by Django 5.2.4 on 2025-10-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medication_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='administration_route',
            field=models.CharField(blank=True, choices=[('ORAL', 'Voie orale'), ('IV', 'Intraveineuse'), ('IM', 'Intramusculaire'), ('SC', 'Sous-cutanée'), ('TOPIQUE', 'Application locale'), ('INHALATION', 'Inhalation'), ('RECTALE', 'Voie rectale'), ('VAGINALE', 'Voie vaginale'), ('OCULAIRE', 'Voie oculaire'), ('NASALE', 'Voie nasale'), ('AUTRE', 'Autre')], max_length=50),
        ),
        migrations.AddField(
            model_name='medication',
            name='care_level',
            field=models.CharField(blank=True, choices=[('SSP', 'Soins de santé primaire'), ('SSS', 'Soins de santé secondaire'), ('TERTIAIRE', 'Soins tertiaires'), ('TOUS', 'Tous niveaux')], max_length=50),
        ),
        migrations.AddField(
            model_name='medication',
            name='designation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='medication',
            name='pathology',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medication',
            name='pharmacotherapeutic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medication',
            name='posology',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='posology_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medication',
            name='precautions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='protocol',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='protocol_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='storage_conditions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medication',
            name='structure_types',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
