# Generated by Django 5.2.4 on 2025-10-25 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medication_administration_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse complète de la formation sanitaire'),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='coverage_polygon',
            field=models.JSONField(blank=True, help_text='Coordonnées du polygone définissant la zone de couverture (format GeoJSON)', null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='coverage_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rayon de couverture en kilomètres (alternatif au polygone)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude de la formation sanitaire', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude de la formation sanitaire', max_digits=11, null=True),
        ),
        migrations.CreateModel(
            name='HealthFacilityDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text="Notes sur l'assignation du distributeur")),
                ('assigned_by', models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'assignation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributors', to='api.healthfacility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_facility_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distributeur de formation sanitaire',
                'verbose_name_plural': 'Distributeurs de formations sanitaires',
                'unique_together': {('user', 'health_facility')},
            },
        ),
    ]
